kodland/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mainapp.urls", namespace='articles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.main, name='index'),
    path('article/<int:pk>/', mainapp.article, name='article'),
    path('add/', mainapp.add, name='add')
]

mainapp/models.py
from django.db import models

# Create your models here.


class Articles(models.Model):
    title = models.CharField(verbose_name='заголовок', max_length=128, blank=True)
    img = models.ImageField(upload_to='article_images', blank=True)
    upload = models.DateTimeField(verbose_name='время', auto_now_add=True)
    short_desc = models.CharField(verbose_name='краткое описание', max_length=256, blank=True)
    article = models.TextField(verbose_name='текст', blank=True)

mainapp/forms.py
from django.forms import ModelForm
from django import forms
from .models import Articles


class NewArticle(ModelForm):
    class Meta:
        model = Articles
        fields = ['title', 'article', 'img', ]
        labels = {'title': '', 'article': '', 'img': ''}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'placeholder': 'Введите название статьи'})
        self.fields['img'].widget.attrs.update({'placeholder': 'ЗАГРУЗИТЕ ИЗОБРАЖЕНИЕ', "onchange": "loadImg(event)"})

mainapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from .forms import NewArticle
from .models import Articles


def main(request, pk=None):
    title = 'главная'
    main_article = Articles.objects.order_by('-upload')[:1]
    other_articles_1 = Articles.objects.order_by('-upload').all()[1:4]
    other_articles_2 = Articles.objects.order_by('-upload').all()[4:7]
    other_articles_3 = Articles.objects.order_by('-upload').all()[7:10]
    content = {
        'title': title,
        'main_article': main_article,
        'other_articles_1': other_articles_1,
        'other_articles_2': other_articles_2,
        'other_articles_3': other_articles_3,
    }
    return render(request, 'mainapp/index.html', content)


def article(request, pk=None):
    title = 'статья'
    data = Articles.objects.filter(pk=pk)
    content = {
        'title': title,
        'data': data,
    }
    return render(request, 'mainapp/article.html', content)


def add(request):
    title = 'опубликовать'
    if request.method == 'POST':
        article_form = NewArticle(request.POST, request.FILES)
        article_form.save()
        return HttpResponseRedirect(reverse('articles:index'))
    else:
        article_form = NewArticle()
    content = {
        'title': title,
        'article_form': article_form,
    }
    return render(request, 'mainapp/add.html', content)

mainapp/templates/mainapp/add.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <script type="text/javascript">
    var loadImg=function(event){
        $('#frame').attr('src', URL.createObjectURL(event.target.files[0]));
    };
    </script>
    <div class="container">
        <div class="article-form">
            <h1>Добавить статью</h1>
            <input type="file" id="files" />

            <form action="{% url 'articles:add' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ article_form.title }}
                <input class="submit-article" type="submit" value="Опубликовать">
                {{ article_form.article }}
                <div class="upload-img">
                    <h2>Загрузить изображение</h2>
                    <button id="img-button" type="button"><p>ФАЙЛ</p>{{ article_form.img }}</button>
                    <img id="frame"  width="298px" height="100px"/>
                </div>

            </form>
        </div>

    </div>

{% endblock %}

mainapp/templates/mainapp/article.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="article-container">
        {% for article in data %}
            <div class="main-article">
                <h1>{{ article.title|safe }}</h1>
                <img src="/media/{{ article.img }}" alt="">
                <h2>{{ article.short_desc|safe }}</h2>
                <p>{{ article.article|safe }}</p>
                <div class="line"></div>
                <h3>Описание фотографии, источник</h3>
                <div class="line"></div>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad aliquid autem commodi ducimus,
                    et illum inventore itaque libero minus nam nulla officiis reprehenderit tempora?</p>
                <div class="quotes">
                    <blockquote class="blockquote-8">
                        <p>Цитата. Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне.</p>
                    </blockquote></div>
                <div class="line"></div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title|title }}</title>

    <link href = "{% static 'fonts/circe/stylesheet.css' %}" rel = "stylesheet" type = "text/css" />
    <link rel="stylesheet" href="{% static 'fonts/museo/museocyrl.css' %}" type = "text/css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdn.tiny.cloud/1/q3i8y4ttupejuagamv04eq1h36hrteh9kafe7i6aa4cpwffn/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({selector: 'textarea',});</script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    {% block menu %}
        <div class="header">
            <div class="container">
                <div class="logo">
                    <a href="{% url 'articles:index' %}">
                        <img src="{% static 'img/Logo_Kodland.png' %}" alt="logo">
                    </a>
                </div>
                <h1 class="title">Блог</h1>
                <a href="{% url 'articles:add' %}"><button class="article-button">+ Добавить статью</button></a>

            </div>
        </div>
    {% endblock %}

    {% block content %}
    {% endblock %}



</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="main-title">
        <div class="container">
            {% for article in main_article  %}
                <div class="title-text">
                    <h3>NEW</h3>

                        <h1>{{ article.title }}</h1>
                        <p>{{ article.short_desc }}</p>

                    <a href="{% url 'articles:article' article.pk %}">
                        <button class="read-article c">Читать</button>
                    </a>

                </div>
                <div class="main-img">
                    <img src="media/{{ article.img }}" alt="">
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="other-titles">
        <div class="container">
            <h2>Другие статьи</h2>
            <div class="other-articles">
                {% for article in other_articles_1 %}
                    <div class="other-article">
                        <a href="{% url 'articles:article' article.pk %}">
                            <div class="other-article-date"><p>{{ article.upload|date:"d F Y H:i"  }}</p></div>
                            <div class="other-article-img"><img src="/media/{{ article.img }}" alt="img"></div>
                            <div class="other-article-title">{{ article.title }}</div>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div class="other-articles">
                {% for article in other_articles_2 %}
                    <div class="other-article">
                        <a href="{% url 'articles:article' article.pk %}">
                            <div class="other-article-date"><p>{{ article.upload|date:"d F Y H:i"  }}</p></div>
                            <div class="other-article-img"><img src="/media/{{ article.img }}" alt="img"></div>
                            <div class="other-article-title">{{ article.title }}</div>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div class="other-articles">
                {% for article in other_articles_3 %}
                        <div class="other-article">
                            <a href="{% url 'articles:article' article.pk %}">
                                <div class="other-article-date"><p>{{ article.upload|date:"d F Y H:i"  }}</p></div>
                                <div class="other-article-img"><img src="/media/{{ article.img }}" alt="img"></div>
                                <div class="other-article-title">{{ article.title }}</div>
                            </a>
                        </div>
                {% endfor %}
            </div>

        </div>
    </div>




{% endblock %}